### ISSUE TITLE
Non fonctionnel

### ISSUE THREAD

**Issue by jcovillers78114** [Kaya84/remotesupport#1]
Bonjour,
Ce plugin semble très intéressant mais n'est pas du ton fonctionnel.

**Comment by Kaya84** [comment]
Can you tell me more about? 
Screenshot? Logs? Describe more please

**Comment by Kaya84** [comment]
Try now. I think is fixed
1) Wrong project name (uppercase)
2) I didn't commented out something related the main class that I'm still working on

**Comment by brusilva84** [comment]
yeah it's fixed.

Would be nice if we can set multiple protocols and the url set's acording to each one.

Made a pull with a fix.

**Comment by jcovillers78114** [comment]
Hi,
Doesn't work anymore.
Now I don't have access to the list of plugins

(glpi 9.5.2)


![image](https://user-images.githubusercontent.com/57490677/142834901-29bfd579-a2ac-48c9-bca0-09e8ec2f73e5.png)

**Comment by Kaya84** [comment]
There was an error from branch merge. 
Seems fixed now. 
Can u check?

**Comment by jcovillers78114** [comment]
I was able to install the plugin.
I created the .bat file
I added the registry key.
I rebooted my computer.

The button is displayed correctly but when I click on it nothing happens.

**Comment by jcovillers78114** [comment]
I also have 2 new links (not translated) that appear on the post form but do not give anything if you click on them

![image](https://user-images.githubusercontent.com/57490677/142844108-ae073a8e-1859-4b9d-aef1-b47670fbf33b.png)

**Comment by Kaya84** [comment]
"Collegati con VNC" is like  "Connect with VNC": does it work?
If both doesn't work, it seems regedit related: can you post a screen of the regedit detail in VNC root?

**Comment by jcovillers78114** [comment]
I add this 

![image](https://user-images.githubusercontent.com/57490677/142844652-a23c5309-adf0-404d-96e6-19509144aee4.png)

But I probably made a mistake because there is nothing in the register

![image](https://user-images.githubusercontent.com/57490677/142844846-36c7d4a4-c70e-4c7e-8b38-a05403ef0b90.png)

**Comment by Kaya84** [comment]
Do it inside regedit.
I see you didn't escape '\' correctly.

**Comment by Kaya84** [comment]
PS: obviously inside "command" folder

**Comment by jcovillers78114** [comment]
Sorry but it doesn't work. I think there is a problem with the registry key.

![image](https://user-images.githubusercontent.com/57490677/142854799-f0b8744e-42fb-4bba-999e-46aab4ddc5dc.png)

**Comment by Kaya84** [comment]
You'r right.
I fixed Readme now.
![immagine](https://user-images.githubusercontent.com/35736369/142862428-1d494cfe-4149-4c04-a925-1bbe85168736.png)

**Comment by jcovillers78114** [comment]
Ok it's works now but only with button 

![image](https://user-images.githubusercontent.com/57490677/142870731-c3f84456-6f21-4836-adb3-a26b91642ee0.png)

If I wanna use the link "" on computer tab there is an error

![image](https://user-images.githubusercontent.com/57490677/142871311-759a935e-2264-4b7d-abe7-56f6c1647c81.png)

it looks like the script called by the link is different from the one for the button and adds the entity to the VNC name

**Comment by Kaya84** [comment]
What's the computer name?
Ths plugin take the computer name and use it as VNC param. 
If you have space in the computer name, it can't work (and DNS system can't do lookup to).
Try rename the item and check inside DNS.

**Comment by jcovillers78114** [comment]
computerTest is the name

That's work with the button on the ticket but not with the link "Collegati con VNC" on computer tab

![image](https://user-images.githubusercontent.com/57490677/142873401-097524b1-1f4e-474a-a85f-fe792077589f.png)

**Comment by jcovillers78114** [comment]
Bug on this (support.js)

name = $(".navigationheader").find("span").first().text().trim();

Seem that not retrieve only the name "computerTest" in the span header but all the span

![image](https://user-images.githubusercontent.com/57490677/142874669-bcfc072b-0297-46f5-bb0e-68b03f9d8b86.png)

**Comment by Kaya84** [comment]
Right. Didn't think this case.
I made (and commit) a quick fix in support.js:
name =  $(".navigationheader").find("span").first().text().split(" ")[0].trim();

Will be better when I will integrate like tickets page

**Comment by jcovillers78114** [comment]
Ok That's working now :)
Link and button
