### ISSUE TITLE
GLPI 10

### ISSUE THREAD

**Issue by r0bertk** [Kaya84/remotesupport#4]
Hello, is compatibility with glpi 10 planned?

**Comment by Kaya84** [comment]
It should.
Next week I hope to have enought time to check.

**Comment by Kaya84** [comment]
There are a couple of things to fix to make ti work with 10. 
I hope to fix in a couple of days.

**Comment by Kaya84** [comment]
Seems fixed.
Can you try now?

**Comment by r0bertk** [comment]
Hello,
when i walk in Setup->General->Remote Support 
I get a message: You don't have permission to perform this action.

**Comment by Kaya84** [comment]
Actually there is no configuration page. 
All the configuration is actually hardcoded.
Hope to make it next week.
