### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by nacordier** [Kaya84/remotesupport#5]
Hello
I have a bug when installing the plugin. It seems that the files with the classes are not available.
(PLuginRemotesupport menu error, etc.)
Can we have these missing files
Thank you

**Comment by Kaya84** [comment]
You were right.
Try it now, it should be fixed.

**Comment by nacordier** [comment]
Thank you very much. It is better

**Comment by Kaya84** [comment]
Fixed
